### ISSUE TITLE
menu is no longer visible

### ISSUE THREAD

**Issue by Notarin** [JessaTehCrow/sandbox_menu#1]
as of recently the menu is no longer visible

**Comment by JessaTehCrow** [comment]
Hello Notarin,

Have you tried downloading the menu from the releases? (https://github.com/JessaTehCrow/sandbox_menu/releases)

The main branch is slightly unstable and might not work 100%.

However if this is not the case, i'd like to get the output of the logger.txt

(found in `steam/steamapps/common/Noita/logger.txt`)

ofcourse you can contact me at "Jessa#8025"
